[package]
name = "wire"
version = "0.1.0"
edition = "2024"

[dependencies]
ash = { git = "https://github.com/ash-rs/ash" }
ash-window = { git = "https://github.com/ash-rs/ash" }
bytemuck = { version = "1.25.2", "features" = ["latest_stable_rust"] }
num = "0.4.3"
winit = "0.31.0-beta.2"

[lints.clippy]
nursery = "warn"
pedantic = "warn"
